<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
<title>Negativity Ray Command Console</title>
<style>
  body, .container, .button-container, .power-warning-container {display: flex; flex-direction: column; align-items: center;}
  body {
    margin: 40px 0; font-family: Arial,sans-serif;
    background: url('https://static.vecteezy.com/system/resources/previews/017/398/142/non_2x/dark-blue-control-panel-abstract-modern-technology-futuristic-interface-hud-design-hud-futuristic-frame-game-target-borders-sci-fi-empty-banners-for-text-menu-technology-interface-vector.jpg') center/cover no-repeat;
    min-height: 100vh; color: #fff; filter: brightness(1.3); position: relative;
    -webkit-font-smoothing: antialiased;
  }
  body::before {
    content:""; position: fixed; inset:0; background: rgba(0,0,0,0.3); z-index: -1;
  }
  .container {width: 95%; max-width: 900px; padding: 0 10px; box-sizing: border-box;}
  .title-container {width: 100%; max-width: 900px; margin: 0.5in 0 20px;}
  .title-main, .title-sub {
    font-weight: 700; color: #004080; letter-spacing: 1.5px; text-transform: uppercase;
    text-align: left; user-select: none; text-shadow: 1px 1px 0 #002040, 2px 2px 0 #001830; margin: 0;
  }
  .title-main {font-size: 2.5rem;}
  .title-sub {font-size: 1.75rem; text-indent: 20px;}
  .timer-container {
    background: rgba(0,0,64,0.88); padding: 15px 40px; border-radius: 12px;
    margin-bottom: 30px; max-width: 320px; width: 100%; text-align: center; position: relative;
  }
  .timer {
    font: bold 3.5rem 'Courier New', monospace; color: #00e6ff; margin: 0; user-select: none;
    -webkit-text-stroke: 1.5px black; text-stroke: 1.5px black;
    text-shadow: 0 0 4px #00e6ff, 0 0 8px #00aabb;
  }
  .self-destruct-overlay {
    position: absolute; inset: 0; background: rgba(0,0,0,0.95);
    color: #0f0; font-family: 'Arial Black', Arial, sans-serif; font-weight: bold;
    font-size: 1.5rem; display: flex; justify-content: center; align-items: center;
    border-radius: 12px; text-align: center; padding: 30px 20px; user-select: none;
    z-index: 10; white-space: pre-line; box-sizing: border-box; line-height: 1.4;
    display: none;
  }
  .button-container {
    margin-bottom: 40px; gap: 20px; flex-wrap: wrap; justify-content: center; align-items: center; width: 100%;
  }
  .btn-glow, #abortBtn {
    cursor: pointer; user-select: none; min-width: 180px; border-radius: 12px;
    font-family: 'Arial Black', Arial, sans-serif; font-weight: bold; padding: 12px 40px;
    font-size: 1.25rem; text-align: center; border: none; flex-shrink: 0; transition: box-shadow 0.3s ease;
  }
  .btn-glow {
    background-color: #ff3300; color: #fff;
    box-shadow: 0 0 20px #ff3300cc, 0 0 40px #ff3300aa, 0 0 60px #ff3300aa;
  }
  .btn-glow:hover {
    box-shadow: 0 0 40px #ff3300dd, 0 0 80px #ff3300cc, 0 0 120px #ff3300cc;
  }
  .btn-glow:active {
    box-shadow: 0 0 60px #ff3300dd, 0 0 100px #ff3300cc, 0 0 140px #ff3300cc;
  }
  .btn-no-glow {
    background-color: #ff3300; color: #fff;
    box-shadow: none;
    cursor: default;
  }
  #abortBtn {
    background-color: #cc0000; border: 2px solid #880000; color: #fff; box-shadow: none;
  }
  #abortBtn:hover {
    box-shadow: 0 0 25px #cc0000dd, 0 0 45px #cc0000bb;
  }
  #audriaBtn {
    display: none;
    background-color: #4B0082; color: white;
    box-shadow: 0 0 20px #8A2BE2cc;
  }
  #audriaBtn:hover {
    background-color: #330055;
    box-shadow: 0 0 30px #8A2BE2eee;
  }
  #audriaBtn:active {
    background-color: #220044;
  }
  .power-warning-container {
    max-width: 360px; width: 100%; margin-top: 20px;
    flex-direction: column; align-items: center;
  }
  .power-meter-container {
    width: 100%; height: 40px; background-color: #222; border-radius: 20px;
    overflow: hidden; box-shadow: inset 0 0 8px #000000cc; user-select: none; box-sizing: border-box;
  }
  .power-meter-fill {
    height: 100%; width: 0%; background: linear-gradient(90deg, #00ff00, #007700);
    transition: width 1s ease; border-radius: 20px 0 0 20px;
  }
  .power-meter-label {
    margin-top: 12px; font-weight: bold; color: #00ff00;
    font-family: 'Courier New', Courier, monospace; text-align: center;
    user-select: none; font-size: 1.25rem; max-width: 100%;
    text-shadow: 0 0 6px #003300; white-space: nowrap;
  }
  .warning-box {
    margin-top: 10px; width: 100%; user-select: none; text-align: center;
    color: #00ff00; font-family: 'Courier New', Courier, monospace;
    font-size: 1rem; font-weight: bold; text-shadow: none; white-space: normal;
  }
  .popup-overlay {
    position: fixed; inset: 0; background: rgba(0,0,0,0.6);
    display: none; justify-content: center; align-items: center; z-index: 1000;
  }
  .popup-box {
    background: white; border-radius: 12px; padding: 20px; box-sizing: border-box;
    user-select: none; max-width: 350px; width: 90%; text-align: center;
    color: purple; font-family: 'Courier New', Courier, monospace;
    font-weight: bold; font-size: 1.3rem; box-shadow: 0 0 20px purple;
  }
  .popup-box button {
    margin-top: 20px; padding: 8px 16px; font-size: 1rem; font-weight: bold;
    border: none; border-radius: 8px; background-color: #4B0082; color: white;
    cursor: pointer; user-select: none; box-shadow: 0 0 10px #8A2BE2cc;
    transition: background-color 0.3s ease;
  }
  .popup-box button:hover {background-color: #330055;}
  #confettiGifContainer {
    position: fixed; top: 50%; left: 50%; transform: translate(-50%, -50%);
    z-index: 2000; display: none; user-select:none;
  }
  #confettiGifContainer img {
    max-width: 100vw; max-height: 100vh; border-radius: 12px;
  }
  @media (max-width:768px){
    body {margin:20px 0;}
    .title-container {margin:0.35in 0 15px;}
    .title-main {font-size:2rem;}
    .title-sub {font-size:1.3rem; text-indent:15px;}
    .timer-container {max-width:280px; padding:12px 25px;}
    .timer {font-size:3rem;}
    .button-container {gap:15px; margin-bottom:30px;}
    .btn-glow, #abortBtn {padding:10px 30px; font-size:1.1rem; min-width:150px;}
    #audriaBtn {min-width:150px;}
    .power-warning-container {max-width:320px; margin-top:15px;}
    .power-meter-label {font-size:1.1rem;}
    .warning-box {font-size:0.95rem;}
    .self-destruct-overlay {font-size:1.3rem; padding:25px 15px;}
  }
  @media (max-width:480px){
    body {margin:15px 0;}
    .title-container {margin:0.25in 0 12px;}
    .title-main {font-size:1.8rem;}
    .title-sub {font-size:1.1rem; text-indent:10px;}
    .timer-container {max-width:260px; padding:10px 20px;}
    .timer {font-size:2.5rem;}
    .button-container {gap:12px; margin-bottom:25px;}
    .btn-glow, #abortBtn {padding:9px 25px; font-size:1rem; min-width:130px;}
    #audriaBtn {min-width:130px;}
    .power-warning-container {max-width:280px; margin-top:12px;}
    .power-meter-label {font-size:1rem;}
    .warning-box {font-size:0.9rem;}
    .popup-box {font-size:1.1rem; max-width:90%; padding:15px 15px 20px 15px;}
    .popup-box button {font-size:0.9rem; padding:7px 14px; margin-top:15px;}
    .self-destruct-overlay {font-size:1.1rem; padding:20px 10px;}
  }
</style>
</head>
<body>
  <div class="container">
    <div class="title-container">
      <h1 class="title-main">Negativity Ray</h1>
      <h2 class="title-sub">Command Console</h2>
    </div>
    <div class="timer-container" id="timerContainer">
      <p class="timer" id="countdown" aria-live="polite" aria-atomic="true" role="timer">04:12:00</p>
      <div class="self-destruct-overlay" id="selfDestructOverlay">Self-destruct Activated</div>
    </div>
    <div class="button-container">
      <button class="btn-glow" id="activateRayBtn" aria-label="Activate Ray button">Ray Activated</button>
      <button class="btn-glow" id="abortBtn" aria-label="Abort Launch button">Abort Launch</button>
      <button class="btn-glow" id="audriaBtn" aria-label="Audria Click Me button">Audria Click Me</button>
    </div>
    <div class="power-warning-container">
      <div class="power-meter-container" aria-label="Power Levels meter" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0" id="powerMeterContainer">
        <div class="power-meter-fill" id="powerMeterFill"></div>
      </div>
      <div class="power-meter-label" id="powerMeterLabel">Charge Indicator Level</div>
      <div class="warning-box" id="warningBox">Once the meter is full, the Negativity Ray will fire on its own — Please stand by</div>
    </div>
  </div>

  <div id="activationPopup" class="popup-overlay" role="dialog" aria-modal="true" tabindex="-1" aria-labelledby="activationMessage" style="display:none;">
    <div class="popup-box">
      <p id="activationMessage"></p>
      <button id="closeActivationPopup">OK</button>
    </div>
  </div>

  <div id="passwordPopup" class="popup-overlay" role="dialog" aria-modal="true" aria-labelledby="passwordLabel" tabindex="-1" style="display:none;">
    <div class="popup-box">
      <label for="passwordInput" id="passwordLabel">Enter Password</label>
      <input type="text" id="passwordInput" autocomplete="off" style="font-size:1rem; padding:8px; width:100%; box-sizing:border-box; margin-top:8px; border-radius:6px; border:1px solid #ccc;" />
      <div class="error-message" id="passwordError" style="color:purple; font-weight:bold; margin-top:10px; min-height:1.2em; user-select:none;"></div>
      <div style="margin-top:20px; display:flex; justify-content:center; gap:15px;">
        <button id="passwordCancelBtn" style="flex:1; min-width:100px;">Cancel</button>
        <button id="passwordSubmitBtn" style="flex:1; min-width:100px;">Submit</button>
      </div>
    </div>
  </div>

  <!-- Confetti GIF container -->
  <div id="confettiGifContainer">
    <img src="https://img1.picmix.com/output/stamp/normal/5/3/2/3/2623235_2a3b2.gif" alt="Confetti" />
  </div>

  <audio id="deactivationSound" src="https://actions.google.com/sounds/v1/weapons/big_explosion_cut_off.ogg" preload="auto"></audio>
  <audio id="wrongSound" src="https://actions.google.com/sounds/v1/cartoon/cartoon_boing.ogg" preload="auto"></audio>

<script>
  const START_SECONDS=4*3600+12*60, countdown=document.getElementById('countdown'),
    abortBtn=document.getElementById('abortBtn'), activateBtn=document.getElementById('activateRayBtn'),
    audriaBtn=document.getElementById('audriaBtn'),
    meterFill=document.getElementById('powerMeterFill'), meterContainer=document.getElementById('powerMeterContainer'),
    passwordPopup=document.getElementById('passwordPopup'), passwordInput=document.getElementById('passwordInput'), passwordError=document.getElementById('passwordError'),
    passCancelBtn=document.getElementById('passwordCancelBtn'), passSubmitBtn=document.getElementById('passwordSubmitBtn'),
    actPopup=document.getElementById('activationPopup'), actMessage=document.getElementById('activationMessage'),
    closeActPopup=document.getElementById('closeActivationPopup'),
    selfDestructOverlay=document.getElementById('selfDestructOverlay'),
    confettiContainer=document.getElementById('confettiGifContainer'),
    deactSound=document.getElementById('deactivationSound'), wrongSound=document.getElementById('wrongSound');

  let totalSeconds=START_SECONDS, timerInt, selfDestruct=false, emptyMeterInt;

  function fmtTime(s){let h=Math.floor(s/3600),m=Math.floor((s%3600)/60),ss=s%60;return[h,m,ss].map(x=>x.toString().padStart(2,'0')).join(':');}
  function updateTimer(){
    if(totalSeconds>=0){
      countdown.textContent=fmtTime(totalSeconds);
      updateMeter();
      totalSeconds--;
    } else {
      clearInterval(timerInt);
      countdown.textContent="00:00:00";
      updateMeter();
      if(!selfDestruct){
        selfDestruct = true;
        showBirthdayPopup();
      }
    }
  }
  function startTimer(){if(timerInt)clearInterval(timerInt);updateTimer();timerInt=setInterval(updateTimer,1000);}
  function stopTimer(){if(timerInt){clearInterval(timerInt);timerInt=null;}}
  function updateMeter(){
    let p = totalSeconds >= 0 ? ((START_SECONDS - totalSeconds) / START_SECONDS) * 100 : 100;
    meterFill.style.width = p + '%';
    meterContainer.setAttribute('aria-valuenow', Math.floor(p));
  }
  function activateSelfDestruct(){
    selfDestruct=true;stopTimer();
    selfDestructOverlay.style.display="flex";countdown.style.visibility="hidden";
    meterFill.style.width="100%";
    meterFill.style.background=`linear-gradient(90deg, rgb(0,255,0), rgb(0,77,0))`;
    meterContainer.setAttribute('aria-valuenow',100);
    startEmptyMeter();
  }
  function startEmptyMeter(){
    let w=100;if(emptyMeterInt)clearInterval(emptyMeterInt);
    const step=100/(10000/50);
    emptyMeterInt=setInterval(()=>{
      w-=step;
      if(w<=0){w=0;clearInterval(emptyMeterInt);}
      meterFill.style.width=w+'%';
      let r=Math.round(255*(1-w/100)),g=Math.round(255*(w/100));
      meterFill.style.background=`linear-gradient(90deg, rgb(${r},${g},0), rgb(${Math.floor(r*0.3)},${Math.floor(g*0.3)},0))`;
      meterContainer.setAttribute('aria-valuenow',Math.floor(w));
    },50);
  }
  // Show birthday popup with custom OK button label "Confettii"
  function showBirthdayPopup(){
    actMessage.textContent = "Happy 10th Birthday Audria";
    actPopup.style.display = "flex";
    closeActPopup.textContent = "Confettii";
    closeActPopup.focus();
  }
  // Show confetti gif container and hide popup
  function showConfettiGif(){
    confettiContainer.style.display = "block";
  }
  // Hide confetti gif container
  function hideConfettiGif(){
    confettiContainer.style.display = "none";
  }
  function handlePassSubmit(){
    let p=passwordInput.value.trim().toLowerCase();
    if(p==="kindness"){
      deactSound.currentTime=0;deactSound.volume=1;deactSound.play();
      hidePassPopup();
      // Remove glow from Ray Activated button
      activateBtn.classList.remove('btn-glow');
      activateBtn.classList.add('btn-no-glow');
      // Show Audria button
      audriaBtn.style.display = 'inline-block';
      setTimeout(activateSelfDestruct,2000);
    } else if(p==="change"){
      totalSeconds=1800; startTimer(); hidePassPopup(); showPopup("Countdown reset to 30 minutes.");
    } else if(p==="5818"){
      hidePassPopup();
      let n=prompt("Enter new countdown time in minutes (1 - 1440):");
      if(n!==null){
        let m=parseInt(n,10);
        if(Number.isInteger(m)&&m>=1&&m<=1440){
          totalSeconds=m*60; startTimer();
          showPopup(`Countdown reset to ${m} minute${m===1?'':'s'}.`);
        } else alert("Invalid time. Please enter a number between 1 and 1440.");
      }
    } else {
      wrongSound.currentTime=0;wrongSound.volume=1;wrongSound.play();
      passwordError.textContent="Nice Try VIPs You Will Never Stop Me";
      passwordInput.focus();passwordInput.select();
    }
  }
  function showPopup(msg){actMessage.textContent=msg;actPopup.style.display="flex";closeActPopup.focus();}
  function hidePopup(){actPopup.style.display="none";}
  function showPassPopup(){passwordError.textContent="";passwordInput.value="";passwordPopup.style.display="flex";passwordInput.focus();}
  function hidePassPopup(){passwordPopup.style.display="none";abortBtn.focus();}

  activateBtn.addEventListener('click',()=>{
    wrongSound.currentTime=0;wrongSound.volume=1;wrongSound.play();
    showPopup("Captain, we are giving it all she's got");
  });
  closeActPopup.addEventListener('click',()=>{
    if(actMessage.textContent === "Happy 10th Birthday Audria"){
      hidePopup();
      showConfettiGif();
      closeActPopup.textContent = "OK";
    } else {
      hidePopup();
      activateBtn.focus();
    }
  });
  actPopup.addEventListener('click',e=>{
    if(e.target===actPopup){
      hidePopup();
      activateBtn.focus();
    }
  });
  abortBtn.addEventListener('click',()=>{if(!selfDestruct)showPassPopup();});
  passCancelBtn.addEventListener('click',hidePassPopup);
  passSubmitBtn.addEventListener('click',handlePassSubmit);
  passwordInput.addEventListener('keydown',e=>{
    if(e.key==='Enter'){e.preventDefault();handlePassSubmit();}
    else if(e.key==='Escape'){e.preventDefault();hidePassPopup();}
  });
  document.addEventListener('keydown',e=>{
    if(e.key==='Escape'){
      if(passwordPopup.style.display==='flex')hidePassPopup();
      if(actPopup.style.display==='flex')hidePopup();
    }
  });

  // Audria button shows birthday popup and confetti
  audriaBtn.addEventListener('click', () => {
    showBirthdayPopup();
  });

  confettiContainer.addEventListener('click', () => {
    hideConfettiGif();
  });

  // Auto-hide confetti after 10 seconds if still visible
  setTimeout(() => {
    if(confettiContainer.style.display === "block"){
      hideConfettiGif();
    }
  }, 10000);

  startTimer(); updateMeter();
</script>
</body>
</html>
